controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
_profiler:
    resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
    prefix: /_profiler
    condition: "context.getMethod() in ['GET', 'HEAD']" # Load profiler only on GET/HEAD requests

app_default:
    path: /{any}
    controller: App\Controller\HomeController::pageNotFound
    requirements:
        any: .*